---
- name: "INSTALLP on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    #host_name: all
    #device_name: /dev/rmt0.1
  collections:
    - ibm.power_aix
  tasks:
    - name: Install software package and expand file systems if necessary
      installp:
        action: "{{action_value}}"
        extend_fs: yes
        device: "{{device_value}}"
        install_list: "{{install_list_value}}"
        updates_only: "{{updates_only_value}}"
