---
- name: "INSTALLP on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    #host_name: all
  collections:
    - ibm.power_aix
  tasks:
    - name: Install software package and expand file systems if necessary
      installp:
        action: commit
        extend_fs: yes
        install_list: "{{install_list_value}}"
