---
- name: "Lists the contents of the media"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    # host_name: all
    # device_value: /mnt
  collections:
    ibm.power_aix

  tasks:
    - name: Media List
      geninstall:
        action: list
        device: "{{device_value}}"
