---
- name: "MOUNT on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    host_name: all
    mount_over_dir_value: /mnt/testfs
  collections:
    ibm.power_aix

  tasks:
    - name: Unmount filesystem
      mount:
        state: umount
        mount_over_dir: "{{mount_over_dir_value}}"
