---
- name: "FILESYSTEM on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    host_name: all
    filesystem_name: /newfs
  collections:
    ibm.power_aix

  tasks:
    - name: Remove a NFS filesystem
      filesystem:
        filesystem: "{{filesystem_name}}"
        state: absent
        rm_mount_point: true
